std_msgs/Header header

##the total disturbance estimation and cross feeding terms

float32  delta_Tx    ## [N]
float32  delta_Ty    ## [N]
float32  delta_Tz    ## [N] 

float32  delta_Rx    ## [N]
float32  delta_Ry    ## [N]
float32  delta_Rz    ## [N] 

float32  R_1x        ## [N]
float32  R_1y        ## [N]
float32  R_1z        ## [N]

float32  R_2x        ## [N]
float32  R_2y        ## [N]
float32  R_2z        ## [N]