std_msgs/Header header

float32  IntegralPose_x    ## [N]
float32  IntegralPose_y    ## [N]
float32  IntegralPose_z    ## [N] 

float32  r_jx    ## [m]
float32  r_jy    ## [m]

float32  v_jx    ## [m]
float32  v_jy    ## [m]

float32  pos_error_x ## [m]
float32  pos_error_y ## [m]
float32  pos_error_z ## [m]

float32  angle_error_x  ## 
float32  angle_error_y  ## 
float32  angle_error_z  ## 

float32  Euler_roll     ##
float32  Euler_pitch    ##
float32  Euler_yaw      ##

float32  u_lx     ##
float32  u_ly     ##
float32  u_lz     ##