string controllername
float32 dronemass
float32 cablelength
float32 a_j
float32 payloadmass
int32 num_drone
float32 t_jx
float32 t_jy
float32 t_jz
float32 kv_xy
float32 Kv_z
float32 kvi_xy
float32 kvi_z
float32 kR_xy
float32 kR_z
float32 kL
float32 Kphi_xy
float32 Kphi_z
float32 pxy_error_max
float32 pz_error_max
float32 pxy_int_max
float32 pz_int_max
float32 tilt_max
float32 int_start_error
float32 fp_max_x
float32 fp_max_y
float32 fp_max_z
---
bool oktostart