string controllername
float32 dronemass
float32 cablelength
float32 a_j
float32 payloadmass
float32 motor_slope
float32 motor_intercept 
int32 num_drone
bool isPubAuxiliaryState
bool isAddonForcedUsed
bool isCrossFeedingTermsUsed
float32 t_jx
float32 t_jy
float32 t_jz
float32 kv_xy
float32 kv_z
float32 kR_xy
float32 kR_z
float32 kL
float32 Kphi_xy
float32 Kphi_z
float32 kr1_x
float32 kr1_y
float32 kr1_z
float32 kr2_x
float32 kr2_y
float32 kr2_z
float32 kp_x
float32 kp_y
float32 kp_z
float32 komega_x
float32 komega_y
float32 komega_z
float32 lambdaj_x
float32 lambdaj_y
float32 lambdaj_z
float32 lambda_T_x
float32 lambda_T_y
float32 lambda_T_z
float32 lambda_R_x
float32 lambda_R_y
float32 lambda_R_z
float32 lambda1_x
float32 lambda1_y
float32 lambda1_z
float32 lambda2_x
float32 lambda2_y
float32 lambda2_z
float32 pxy_error_max
float32 pz_error_max
float32 pxy_int_max
float32 pz_int_max
float32 tilt_max
float32 int_start_error
float32 fp_max_x
float32 fp_max_y
float32 fp_max_z
---
bool oktostart